version: '3'
services:
  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    environment:
      SERVER_PORT: 80
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    environment:
      SERVER_PORT: 80
      BACKEND_HOST: http://backend
    ports:
      - "8000:80"
 